In [2]:
from starkiller import sat_killer
import cv2
import matplotlib.pyplot as plt
import matplotlib
#%matplotlib notebook
matplotlib.use('Agg')
from glob import glob
import numpy as np

In [3]:
files = glob('muse_preview_archive/*.png')

In [4]:
x1 = 106+20; x2 = 701-20
y1 = 150+20; y2 = 729-20

for file in files:
    try:
        image = cv2.imread(file,0)
        cutout = image[y1:y2,x1:x2]
        name = 'sat_streaks/' + file.split('/')[-1]
        sat = sat_killer(1,1,run=False)
        sat.quick_detection(cutout,5,savename=name)
    except:
        print('junk: ',file)

junk:  muse_preview_archive/ADP.2019-10-03T20:48:41.991.png
junk:  muse_preview_archive/ADP.2021-11-26T15:26:27.582.png
junk:  muse_preview_archive/ADP.2019-10-02T07:20:55.900.png
junk:  muse_preview_archive/ADP.2019-11-21T05:51:27.904.png
junk:  muse_preview_archive/ADP.2019-09-28T13:26:39.655.png
junk:  muse_preview_archive/ADP.2021-11-26T15:26:27.571.png


In [ ]:
for sat in sats:
    name = 'muse_preview_archive/' + sat.split('/')[-1]
    os.system(f'cp {name} muse_archive_sats')

In [322]:
close = 30
nlines = 1

c = np.sqrt((yyy[:,np.newaxis,:,np.newaxis] - yyy[np.newaxis,:,np.newaxis,:])**2 
            + (xxx[:,np.newaxis,:,np.newaxis] - xxx[np.newaxis,:,np.newaxis,:])**2)
c[c==0] = np.nan

dmatrix = np.nanmean(np.nanmin(c,axis=2),axis=2)
np.fill_diagonal(dmatrix,0)
d_bool = dmatrix < close
d_bool = np.unique(d_bool,axis=0)
ind = np.sum(d_bool,axis=1) > nlines
d_bool = d_bool[ind]

In [323]:
d_bool

array([[False,  True,  True]])

In [297]:
np.fill_diagonal(dmatrix,0)

In [299]:
d_bool = dmatrix < 20

In [307]:
d_bool = np.unique(d_bool,axis=0)


In [302]:
np.unique(d_bool,axis=1)a
db

array([[False,  True],
       [ True, False],
       [ True, False]])

In [ ]:
np.nanmin

In [272]:
c = yyy[:,np.newaxis,np.newaxis] - yyy[np.newaxis,:,np.newaxis,:,np.newaxis]

In [273]:
c.shape

(1, 3, 1, 221, 1)

In [268]:
b.shape

(1, 3, 1, 221, 221)

In [ ]:
for l in yyy:
    yyy[:,np.newaxis] - l[]

In [201]:
eh.shapea


(3, 3, 221, 221)

In [209]:
eh[:,:,10,1]

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [192]:
a = np.nanmin(eh,axis=2)

In [193]:
a.shape

(3, 3, 221)

In [194]:
np.nanmedian(a,axis=2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [195]:
eh.shape

(3, 3, 221, 221)

In [42]:
coefs[:,0][:,np.newaxis]*coefs[:,0][np.newaxis,0]

array([[0.00470973],
       [0.80738178],
       [0.77657379]])

In [ ]:
import numpy as np


In [ ]:
plt.figure()
plt.imshow(sat.image,origin='lower',cmap='gray',vmin=np.nanpercentile(sat.image,16),vmax=np.nanpercentile(sat.image,95))
for line in sat.lines:
    x1, y1, x2, y2 = line[0]
    plt.plot([x1,x2],[y1,y2],'C1')

In [ ]:
sat.plot_lines()
#plt.savefig('thumbnail_test.png')